// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using interview.Model;

#nullable disable

namespace interview.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231225144425_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("interview.Model.ReviewSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LikeToContact")
                        .HasColumnType("bit");

                    b.Property<decimal>("Question1Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Question2Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Question3Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Question4Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<string>("SessionRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmissionDateTim")
                        .HasColumnType("datetime2");

                    b.Property<int>("TherapistRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("reviewSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
